### ISSUE TITLE
Copyright Infringement!

### ISSUE THREAD

**Issue by adamgoodrich** [MonoDepth/HamsterFPS#1]
Hi,

You have probably mistakenly included a copy of my asset Gaia in a public repository. 

I have spent over a year working on Gaia and you are making it simple and free for anyone to download. Please remove it immediately. 

I will wait 24 hours and if it has not been removed I will pursue this as intentional copyright infringement.

Thanks,
Adam.

**Comment by MonoDepth** [comment]
Oh, yes you're right, I forgot that the map was made with gaia when I uploaded it, will remove it first thing I do when I have access to a pc with a backup on it (which would be in ~8 hours), Sorry for the trouble.

Cheers,
MonoDepth.

**Comment by adamgoodrich** [comment]
Thanks ☺

**Comment by MonoDepth** [comment]
Should be removed now, hope I didn't cause to much trouble ☺

Cheers,
MonoDepth.

**Comment by adamgoodrich** [comment]
Thanks ☺
